export interface MUSMappings {
  records: MUSMapping[];
}
export class MUSMapping {
  ID = 0;
  NAME = '';
  KIND = 0;
  ENTITYID = 0;
  VALUEID = 0;
  LEVEL = 0;

  static NAME_USLANG = 'USLANG';
  static NAME_USROWSPERPAGEOPTIONS = 'USROWSPERPAGEOPTIONS';
  static NAME_USROWSPERPAGE = 'USROWSPERPAGE';

  static NAME_USTEXTBOOK = 'USTEXTBOOK';
  static NAME_USDICTREFERENCE = 'USDICTREFERENCE';
  static NAME_USDICTNOTE = 'USDICTNOTE';
  static NAME_USDICTTRANSLATION = 'USDICTTRANSLATION';
  static NAME_USVOICE_WEB = 'USWEBVOICE';
  static NAME_USVOICE_IOS = 'USIOSVOICE';
  static NAME_USVOICE_ANDROID = 'USANDROIDVOICE';

  static NAME_USUNITFROM = 'USUNITFROM';
  static NAME_USPARTFROM = 'USPARTFROM';
  static NAME_USUNITTO = 'USUNITTO';
  static NAME_USPARTTO = 'USPARTTO';
}
